export enum CategoryActionType {
    SHOW_FORM = 'CATEGORY/SHOW_FORM',
    FETCH_INIT = 'CATEGORY/FETCH_INIT',
    FETCH_SUCCESS = 'CATEGORY/FETCH_SUCCESS',
    FETCH_CANCEL = 'CATEGORY/FETCH_CANCEL',
    FETCH_FAILED = 'CATEGORY/FETCH_FAILED',
    PROCESSING_INIT = 'CATEGORY/PROCESSING_INIT',
    PROCESSING_DONE = 'CATEGORY/PROCESSING_DONE',
    PROCESSING_FAILED = 'CATEGORY/PROCESSING_FAILED'
}
