export enum CategoryActionType {
    SHOW_MODAL = 'CATEGORY/SHOW_MODAL',
    HIDE_MODAL = 'CATEGORY/HIDE_MODAL',
    FETCH_INIT = 'CATEGORY/FETCH_INIT',
    FETCH_SUCCESS = 'CATEGORY/FETCH_SUCCESS',
    FETCH_CANCEL = 'CATEGORY/FETCH_CANCEL',
    FETCH_FAILED = 'CATEGORY/FETCH_FAILED',
    PROCESSING_INIT = 'CATEGORY/PROCESSING_INIT',
    PROCESSING_DONE = 'CATEGORY/PROCESSING_DONE',
    PROCESSING_FAILED = 'CATEGORY/PROCESSING_FAILED',
    REFRESH = 'CATEGORY/REFRESH'
}
