export enum ModalActionType {
    SHOW = 'MODAL/SHOW',
    INITIALIZE_DONE = 'MODAL/INITIALIZE_DONE',
    INITIALIZE_FAILED = 'MODAL/INITIALIZE_FAILED',
    HIDE = 'MODAL/HIDE',
    PROCESSING_INIT = 'MODAL/PROCESSING_INIT',
    PROCESSING_FAILED = 'MODAL/PROCESSING_FAILED',
    PROCESSING_DONE = 'MODAL/PROCESSING_DONE'
}
