export enum CategoriesActionType {
    FETCH_INIT = 'CATEGORIES/FETCH_INIT',
    FETCH_SUCCESS = 'CATEGORIES/FETCH_SUCCESS',
    FETCH_CANCEL = 'CATEGORIES/FETCH_CANCEL',
    FETCH_FAILED = 'CATEGORIES/FETCH_FAILED',
    ITEM_UPDATE = 'CATEGORIES/ITEM_UPDATE',
    ITEM_INSERT = 'CATEGORIES/ITEM_INSERT',
    ITEM_REMOVE = 'CATEGORIES/ITEM_REMOVE'
}
