export enum ReportActionType {
    REPORT_FETCH_INIT = 'REPORT/FETCH_INIT',
    REPORT_FETCH_SUCCESS = 'REPORT/FETCH_SUCCESS',
    REPORT_FETCH_FAILED = 'REPORT/FETCH_FAILED',
    REPORT_SET_FILTER = 'REPORT/REPORT_SET_FILTER',
    REPORT_RESET = 'REPORT/REPORT_RESET'
}
