name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: our-expenses-fe
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/our-expenses-fe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Configure GCloud in Github Actions environment
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker to use GCloud CLI
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$SHORT_SHA \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$SHORT_SHA

      - name: Deploy Docker image
        run: |
          gcloud run deploy $SERVICE_NAME --image $IMAGE_NAME:$SHORT_SHA \
                                          --region europe-west1 \
                                          --platform managed \
                                          --allow-unauthenticated
