export enum ExpenseActionType {
    CATEGORIES_FETCH_INIT = 'EXPENSE/CATEGORIES/FETCH_INIT',
    CATEGORIES_FETCH_SUCCESS = 'EXPENSE/CATEGORIES/FETCH_SUCCESS',
    CATEGORIES_FETCH_FAILED = 'EXPENSE/CATEGORIES/FETCH_FAILED',
    CREATE_INIT = 'EXPENSE/CREATE_INIT',
    CREATE_DONE = 'EXPENSE/CREATE_DONE',
    CREATE_FAILED = 'EXPENSE/CREATE_FAILED'
}
